# Generated by Django 4.2.6 on 2023-10-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome Padrão', max_length=100, verbose_name='Nome')),
                ('materia', models.CharField(max_length=100, verbose_name='Matéria')),
                ('turma', models.CharField(max_length=100, verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
