# Generated by Django 4.2.6 on 2023-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='dataNasc',
            field=models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento'),
        ),
    ]
