# Generated by Django 4.2.6 on 2023-10-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='serie',
            new_name='ano',
        ),
    ]
