# Generated by Django 4.2.6 on 2023-12-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_remove_aluno_email_remove_professor_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='leciona',
            new_name='turma',
        ),
    ]
