# Generated by Django 4.2.6 on 2023-10-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_professor_datanasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome Padrão', max_length=100, verbose_name='Nome')),
                ('matricula', models.IntegerField(max_length=100, unique=True, verbose_name='Matrícula')),
                ('turma', models.CharField(max_length=100, verbose_name='Turma')),
                ('dataNasc', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
