# Generated by Django 4.2.6 on 2023-10-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(unique=True, verbose_name='Matrícula'),
        ),
    ]
