# Generated by Django 4.2.6 on 2023-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_alter_aluno_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Projeto', 'Projeto'), ('Recado', 'Recado')])),
                ('descricao', models.TextField(unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='TipoPubli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolhaTipo', models.CharField(blank=True, choices=[('Projeto', 'Projeto'), ('Recado', 'Recado')], max_length=50, verbose_name='Escolha')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='Nome', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(default='Nome', max_length=100, verbose_name='Nome'),
        ),
    ]
